# netlify.toml - Updated with your actual API paths

# Build configuration
[build]
  command = "npm install html2canvas --save && npm run build"
  publish = "build"

# Build environment variables
[build.environment]
  CI = "false"

# Redirect API requests to your Heroku backend
[[redirects]]
  from = "/api/maps/*"
  to = "https://roof-measure-5164a9a88417.herokuapp.com/api/maps/:splat"
  status = 200
  force = true

# Fallback for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
