[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  [build.environment]
  CI = "false"
  [build]
  command = "npm install html2canvas --save && npm run build"
  publish = "build"  # adjust if your publish directory is different
