# netlify.toml
[build]
  command = "npm run build"
  publish = "build"

# Build environment variables
[build.environment]
  # This tells create-react-app to ignore linting during build
  CI = "false"
  # Set default API URL for fallback
  REACT_APP_API_URL = "https://roof-measure-5164a9a88417.herokuapp.com"
  # Increase Node memory limit to prevent build failures with large dependencies
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Force Netlify to use Node 16 which has better compatibility with these packages
  NODE_VERSION = "16"

# Redirect API requests to your backend server
[[redirects]]
  from = "/api/*"
  to = "https://roof-measure-5164a9a88417.herokuapp.com/api/:splat"
  status = 200
  force = true

# Add specific redirect for CSS files that might be dynamically imported
[[redirects]]
  from = "/static/css/*"
  to = "/static/css/:splat"
  status = 200

# Add redirect for node_modules content that might be needed at runtime
[[redirects]]
  from = "/node_modules/*"
  to = "/node_modules/:splat"
  status = 200
  
# Fallback for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
