# netlify.toml
[build]
  command = "npm run build"
  publish = "build"

# Build environment variables
[build.environment]
  # This tells create-react-app to ignore linting during build
  CI = "false"
  # Set default API URL for fallback
  REACT_APP_API_URL = "https://roof-measure-5164a9a88417.herokuapp.com"

# Redirect API requests to your backend server
[[redirects]]
  from = "/api/*"
  to = "https://roof-measure-5164a9a88417.herokuapp.com/api/:splat"
  status = 200
  force = true

# Fallback for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
